---
title: "Assignment 8"
author: "Bakari Moitt"
date: "2023-01-26"
output: html_document
---

Code Reflection:

Reflecting on Assignment 6:
```{r}
##### Looking at question 1, I chose the structure function instead of glimpse. I think either is fine, I just prefer the structure function because it is easier for me to read and it gave me exactly what I needed to asnwer the question.   

##### For question 2, I felt that I liked my chose of excluding Setosa rather than including only Virginica and Versicolor because it was slightly shorter code.

##### For question 3, I think both methods work well. I liked my choice in using the exclusion instead of typing what i wanted to include. For, the exclusion method is just a bit easier, but they both work. 

##### For question 4, I wrote the same thing that the answer key has written

##### For question 5, I had glimpse written initially, but because I didn't think we needed to keep it, I just deleted that bit of code and wrote down the necessary answer. Otherwise, the code is the same. 

##### For question 6, I gave my columns different names but the code what the same. 

##### For question 7, The code was the same, I did get help from the professor for this question, I did not really understand how to sub-categorize at first. Instead of typing print, I just wrote iris5 so it would show up anyways. 

##### For question 8, I was stumped for a while. I missed the class on using the piping operation, but once I got it, it worked out perfectly. I did not realize that you could type the arrange code without typing 'by='. All in all, not a very difficult assignment. 

```

Reflecting on Weekly Assignment 2:
```{r}
##### For Part 1 & 2, making the function, I chose to try to create my own function so that I could fill in the preferred mean and SD for the data set. I was not really sure how to do this otherwise. That worked out pretty well. After having the professor look at it, I was able to combine the functions and create one large function as you can see below. Instead of having type and value be separate functions, they are all in one, alongside the data frame being created. 

#this is before
#Type
Type <- rep(c("Control", "Treatment"), each=25) 

#value
glue <- function(n, mean, sd) {   
as.vector(mean + sd * scale(rnorm(n)))
}
set.seed(124)
Value <- c(glue(25, 10, 1.5), glue(25, 25, 2))
dFrame <- data.frame(Type, Value)
head(dFrame)
  
# this is after:     
set.seed(123)
glue <- function(n=25, mean1=10, sd1=1.5, n2=25,mean2=45,sd2=2) {
  type <- rep(c("Control", "Treatment"), each = n) 
  value <- c(rnorm(n, mean = mean1, sd = sd1), rnorm(n2, mean=mean2, sd=sd2)) # by using c function, I can create Value using the function above and rnorm
  dframe <- data.frame(type, value)
  return(dframe)
  }
data <-glue()


##### For part 3 and 4, I did conduct an anova but I didn't create a variable for the summary so the information would not remain if I changed the data set. The function fo the p-value also would not run by itself. 

# this is before

oneway <- aov(Value ~ Type, data= dFrame)
summary(oneway)

summary(oneway)[[1]][1,5]
# at this point, the function cannot be recreated easily. It will operation as its own vector

# this is after
P <- function(dframe=NULL) { # this null ensures that the function will only operate when there is information in it
  oneway <-aov(value ~ type, data = dframe)
  testSummary<- summary(oneway)
  p_value <- testSummary[[1]][["Pr(>F)"]][1] # this ensures that regardless of changes to the data set, I can still get the p-value for any summary ran
  return(p_value)
}
P(dframe=data)
#during this section, I failed to make the anova test and resulting p-value able to be repeated regardless of data set
```


Code Annotation:
```{r}
## Set up libraries
library(tidyverse)
library(ggthemes)


# Data obtained from Veysey Powell and Babbitt 2016: An experimental test of buffer utility as a technique for managing pool-breeding amphibians https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.547rp

dryadData <- read.table(file="data/veysey-babbitt_data_amp.csv", header = TRUE, sep = ",")
glimpse(dryadData) # the glimpse function 
head(dryadData)
# this is meant to call on the data from the dryad website about experimental test on amphibians breeding.

table(dryadData$species) 

dryadData$species<-factor(dryadData$species, labels=c("Spotted Salamander", "Wood Frog")) #creating 'labels' to use for the plot so that the species will be broken down into two separate species


#class(dryadData$treatment)
dryadData$treatment <- factor(dryadData$treatment, 
            levels=c("Reference",
                     "100m", "30m")) #looking at the treatment column of dryadData, the factor calls and renames the 3 possible data sections in the treatment column to Reference, 100m, and 30m.

p<- ggplot(data=dryadData, # this says that you would like a plot or graph to be made
       aes(x=interaction(wetland, treatment), # the x values will be the wetland and treatment columns
           y=count.total.adults, fill=factor(year))) + geom_bar(position="dodge", stat="identity", color="black") + # the y values will be the total adult count. geom_bar is requesting a bar graph where the position is dodge which is telling the bard to avoid overlapping with one another and the stats set to identity tell ggplot to leave the data as is while the color for the bars are black
  ylab("Number of breeding adults") + # the x-axis is named Number of breeding adults
  xlab("") + # the y-axis is unnamed
  scale_y_continuous(breaks = c(0,100,200,300,400,500)) + #this gives the breakdown for the scale of the y-axis where there is a continuous scale of numbers beginning with 0 ending with 500 and then more in between as read above
  scale_x_discrete(labels=c("30 (Ref)", "124 (Ref)", "141 (Ref)", "25 (100m)","39 (100m)","55 (100m)","129 (100m)", "7 (30m)","19 (30m)","20 (30m)","59 (30m)")) + # this is the scale for the x axis where there are specific numbers that do not represent a numerical scale, but more so characterizing values.
  facet_wrap(~species, nrow=2, strip.position="right") + # this separates the bar plot into two separate graphs based on the 2 species in the species column of dryadData. The strip position puts them on the rights side and nrow=2 represent the number of rows in the species columns (like the options)
 theme_few() + scale_fill_grey() + #this establishes a grey scale for the graphs
theme(panel.background = element_rect(fill = 'gray94', color = 'black'), #this fills the background fo the panel with shade gray94 and the outline becomes black
legend.position="top",  legend.title= element_blank(), axis.title.y = element_text(size=12, face="bold", colour = "black"), strip.text.y = element_text(size = 10, face="bold", colour = "black")) + #makes the legend go to the top with legend.position. for the strip text, the size was adjusted to be 10, the font size was made to be bold, and the print color was made to b black
  guides(fill=guide_legend(nrow=1,byrow=TRUE))  #the legend is adjusted to be in line with the graph rather than away from it

p
```





